### PR TITLE
Matching expected return for getRequiresAdditionalSellerInputs

### PR DESCRIPTION
**Pull request by rradutzu**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>ShippingService -> getRequiresAdditionalSellerInputs - match return type</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

### CODE REVIEW

**Comment by jasonhebert** [comment]
This is a no-go. The modified file is a generated file noted in the comments at the top of the file. The file is generated based on model definition files provided by Amazon here: https://github.com/amzn/selling-partner-api-models

If the definition file needs to be changed I would suggest submitting a PR to that repo with the desired fix.

Thanks...

**Comment by jasonhebert** [comment]
OR, if you think the template the parser uses to generate the file in this repo (in resources/php-amazon-selling-partner-api) needs updated please correct and submit PR here for the change.

**Comment by rradutzu** [comment]
After running the bin/generate.sh in my local repo, the issue seems to have resolved itself. I will create a new pull request with all updated models based on the latest run of bin/generate.sh.

Thanks

**Comment by norberttech** [comment]
Let me then do it for you and release another path, Amazon probably recently updated their models and I missed that, thanks for the heads up!

**Pull request closed without merging**
