### PR TITLE
Move tools composer to main composer

### PR DESCRIPTION
**Pull request by KasperFranz**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
  <li>Moved dev requirements from the tools composer to  the main composer.</li> 
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

### CODE REVIEW

**Comment by norberttech** [comment]
I'm personally strongly against this one, I found it easier to maintain projects when tools dependencies are not overlapping with lib dependencies. I used to had many problems in the past with compatibility and since then I decided to keep tools separated which I consider a good practice and clean approach to the problem.

**Comment by KasperFranz** [comment]
> to maintain projects when tools dependencies are not overlapping with lib dependencies. I used to had many problems in the past with compatibility and since then I decided to keep tools separated which I consider a good practice and clean approach to the problem.

Can you elaborate, please? The tools are used to maintain the package, and having it in a different composer feels wrong to me

**Comment by norberttech** [comment]
> > to maintain projects when tools dependencies are not overlapping with lib dependencies. I used to had many problems in the past with compatibility and since then I decided to keep tools separated which I consider a good practice and clean approach to the problem.
> 
> Can you elaborate, please? The tools are used to maintain the package, and having it in a different composer feels wrong to me

Simple example, library depends on another library, lets call it X, one of the tools also depends on that X library, so now your library is essentially limited by the dependency of your tool, something that is not even used in your code. If that tool lock that dependency to lets say version 1.* and you would like to support all between 1.* and 2.* you would not have a way to test it since composer will not even let you download 2.* because it was limited by one of your dependencies. 

And that problem goes even deeper, because dependencies of your dependencies might also have their own dependencies that might be as well your dependencies which makes it even more complicated later.

**Comment by KasperFranz** [comment]
Require-dev is, by definition, required to generate and build the application.
Pushing some of those requirements to a separate folder makes it hard to maintain.

Your library is limited as part of the development to versions that your tools require; yes, but most dependencies will allow multiple versions of a tool (e.g. friendsofphp/php-cs-fixer requirement to Symfony packages).

**Comment by norberttech** [comment]
> Pushing some of those requirements to a separate folder makes it hard to maintain.

Could you elaborate? I maintain all of my packages this way, including some commercial projects maintained by multiple people. Nobody (including me) ever complained about anything related to separating tools from dependencies. I’m curious if I’m missing something.

> yes, but most dependencies will allow multiple versions of a tool (e.g. friendsofphp/php-cs-fixer requirement to Symfony packages).

well if that were true, projects like phive or Scoper or  composer-bin-plugin would never exist 😅 like I said before, I already went through hell dealing with conflicts from tools. 
 
Obviously whoever would take over maintenance of this library can later decide to change it, and merge everything to composer.json but during the transition period that might require me to get involved, I would prefer to keep it the way it is.

**Pull request closed without merging**
